language: python

python:
  - '3.6'

cache:
  pip: true
  directories:
    - .pytest_cache

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt -q
script:
  - export PYTHONPATH=$PWD
  - pytest tests
